config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables, only: [:create, :edit, :destroy]
  patch 'payed/:id', to: 'sale_updates#payed', as: 'payed'
  patch 'given/:id', to: 'sale_updates#given', as: 'given'
  patch 'ready/:id', to: 'sale_updates#ready', as: 'ready'
  patch 'done/:id', to: 'sale_updates#done', as: 'done'
  resources :orders, only: [:create]
  resources :tables, only: [:new, :create, :destroy, :edit, :update]
  delete 'orders/:id', to: 'orders#delete', as: 'delete_order'
  get 'dashboards/commerce', to: 'dashboards#commerce_index'
  get 'dashboards/commerce_sales'
  get 'dashboards/commerce_kitchen'
  get 'dashboards/commerce_generals'
  get 'dashboards/workers', to: 'dashboards#workers_index'
  get 'dashboards/workers_kitchen'
  get 'dashboards/workers_products'
  get 'dashboards/workers_sales'
  resources :orders, only: [:create, :delete]
  resources :sales
  resources :orders, only: [:update, :delete]
  resources :products
  devise_for :workers, controllers:
      {registrations: 'workers/registrations',
      sessions: 'workers/sessions',
      passwords: 'workers/passwords'}
  resources :workers
  resources :offices
  devise_for :commerces, controllers:{
      registrations: 'commerces/registrations',
      sessions: 'commerces/sessions',
  passwords: 'commerces/passwords'}
  resources :commerces
  get 'landing', to: 'landing#index'
  get 'landing/features', to: 'landing#features', as: 'features'
  get 'landing/pricing', to: 'landing#pricing', as: 'pricing'
  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/worker.rb
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :office, optional: true
  belongs_to :commerce
  has_many :sales, dependent: :nullify
  has_one_attached :image, dependent: :destroy

  validates :rol, uniqueness: true, presence: true
  validates :name, presence: true
end

app/controllers/workers/confirmations_controller.rb
# frozen_string_literal: true

class Workers::ConfirmationsController < Devise::ConfirmationsController
  skip_authorize_resource
  skip_authorization_check
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/workers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Workers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/workers/passwords_controller.rb
# frozen_string_literal: true

class Workers::PasswordsController < Devise::PasswordsController
  skip_authorize_resource
  skip_authorization_check
  respond_to :html, :js
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/workers/registrations_controller.rb
# frozen_string_literal: true

class Workers::RegistrationsController < Devise::RegistrationsController
  skip_authorize_resource
  skip_authorization_check
  respond_to :html, :js
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     build_resource(sign_up_params)
     if resource.save
       yield resource if block_given?
       if resource.persisted?
         if resource.active_for_authentication?
           set_flash_message! :notice, :signed_up
           sign_up(resource_name, resource)
           UserNotifierMailer.send_signup_email(resource).deliver
           respond_with resource, location: after_sign_up_path_for(resource)
         else
           set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
           expire_data_after_sign_in!
           respond_with resource, location: after_inactive_sign_up_path_for(resource)
         end
       else
         clean_up_passwords resource
         set_minimum_password_length
         respond_with resource
       end
     else
       redirect_to request.referrer, alert: 'Hubo un error en su registro, ingrese los datos correctamente'
     end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
     self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
     prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

     resource_updated = update_resource(resource, account_update_params)
     yield resource if block_given?
     if resource_updated
       set_flash_message_for_update(resource, prev_unconfirmed_email)
       bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

       respond_with resource, location: request.referrer, notice: 'Perfil Actualizado'
     else
       clean_up_passwords resource
       set_minimum_password_length
       redirect_to request.referrer, alert: 'Su perfil no pudo ser actualizado'
     end
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:office_id, :name, :rol, :adress, :number, :admin, :commerce_id])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:office_id, :name, :rol, :adress, :number, :admin, :image])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workers/sessions_controller.rb
# frozen_string_literal: true

class Workers::SessionsController < Devise::SessionsController
  skip_authorization_check
  respond_to :html, :js
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected

  def after_sign_in_path_for(resource)
    super(resource)
    dashboards_workers_path
  end

  def after_sign_out_path_for(resource)
    super(resource)
    root_path
  end
end

app/controllers/workers/unlocks_controller.rb
# frozen_string_literal: true

class Workers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  load_and_authorize_resource

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to request.referrer, notice: 'El trabajador de ha actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @worker }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:office_id, :name, :rol, :adress, :number, :admin)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/workers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar Sesión", new_session_path(resource_name), data:{remote: true} %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "¿Olvidaste tu contraseña?", new_password_path(resource_name), data:{remote: true} %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/workers/shared/_navbarworker.html.erb
<div id="wrapper" class="toggled">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <br>
      <li class="sidebar-brand text-center text-white">
        <h3 class="bg-info pl-5">Kitchain</h3>
      </li>
      <li>
        <%= link_to 'Dashboard', dashboards_workers_path, class:'btn btn-info text-left text-white col-lg-12 mt-1', id:'nav-side-button'%>
      </li>
      <li>
        <%= link_to 'Ventas', dashboards_workers_sales_path, class:'btn btn-info text-left text-white col-lg-12 mt-1', id:'nav-side-button' %>
      </li>
      <li>
        <%= link_to 'Productos y mesas', dashboards_workers_products_path, class:'btn btn-info text-left text-white col-lg-12 mt-1', id:'nav-side-button' %>
      </li>
      <li>
        <%= link_to 'Cocina', dashboards_workers_kitchen_path, class:'btn btn-info text-left text-white col-lg-12 mt-1', id:'nav-side-button' %>
      </li>
      <hr>
      <li>
        <a href='#menu-toggle' class="btn btn-primary menu-toggle  text-left  text-white col-lg-12" id="nav-side-button">Ocultar menú</a>
      </li>
      <hr>
      <li>
        <h5 class="text-white text-center">
          <%= current_worker.name %>
        </h5>
      </li>
      <li>
        <% if current_worker.image.attached? %>
          <%= image_tag(current_worker.image, class:"img-thumbnail", style:"height: 15vh; margin-left: 25%; width: 15vh") %>
        <% else %>
          <img src="https://image.freepik.com/vector-gratis/perfil-avatar-hombre-icono-redondo_24640-14044.jpg" class="img-thumbnail" style="max-height: 15vh; margin-left: 25%">
        <% end %>      </li>
      <br>
      <li>
        <h5 class="text-white">
          <%= link_to 'Editar Perfil', edit_worker_registration_path, data: {remote: true}, class:'btn btn-light col-sm-12 text-left p-1', id:'nav-side-button'  %>
        </h5>
      </li>
      <li>
        <h5 class="text-white text-center">
          <%= link_to 'Salir', destroy_worker_session_path, method: :delete, class:'btn btn-light col-sm-12  text-left p-1', id:'nav-side-button'  %>
        </h5>
      </li>
    </ul>
  </div>

  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <!-- /#page-content-wrapper -->

</div>

<div class="sticky">
  <a href='#menu-toggle' class="btn btn-success menu-toggle pl-5 pr-5 ml-3">Menú</a>
</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
    $(document).ready(function() {
        $(".menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        if($(document).width() > 600){
            $('.container').on('click',function() {
                if($("#wrapper").attr('class') == ""){
                    $("#wrapper").attr('class', 'toggled');
                }
            })
        }});
</script>