config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables, only: [:create, :edit, :destroy]
  patch 'payed/:id', to: 'sale_updates#payed', as: 'payed'
  patch 'given/:id', to: 'sale_updates#given', as: 'given'
  patch 'ready/:id', to: 'sale_updates#ready', as: 'ready'
  patch 'done/:id', to: 'sale_updates#done', as: 'done'
  resources :orders, only: [:create]
  resources :tables, only: [:new, :create, :destroy, :edit, :update]
  delete 'orders/:id', to: 'orders#delete', as: 'delete_order'
  get 'dashboards/commerce', to: 'dashboards#commerce_index'
  get 'dashboards/commerce_sales'
  get 'dashboards/commerce_kitchen'
  get 'dashboards/commerce_generals'
  get 'dashboards/workers', to: 'dashboards#workers_index'
  get 'dashboards/workers_kitchen'
  get 'dashboards/workers_products'
  get 'dashboards/workers_sales'
  resources :orders, only: [:create, :delete]
  resources :sales
  resources :orders, only: [:update, :delete]
  resources :products
  devise_for :workers, controllers:
      {registrations: 'workers/registrations',
      sessions: 'workers/sessions',
      passwords: 'workers/passwords'}
  resources :workers
  resources :offices
  devise_for :commerces, controllers:{
      registrations: 'commerces/registrations',
      sessions: 'commerces/sessions',
  passwords: 'commerces/passwords'}
  resources :commerces
  get 'landing', to: 'landing#index'
  get 'landing/features', to: 'landing#features', as: 'features'
  get 'landing/pricing', to: 'landing#pricing', as: 'pricing'
  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(worker)
    if worker.admin?
      can [:create], [Sale, Order, Product, Worker, Table]
      can [:delete], [Worker, Sale, Product], office_id: worker.office.id
      can :manage, [Sale, Table, Product], office_id: worker.office.id
      can :manage, [Order], sale_id: worker.office.sales.ids
    else
      can [:create], [Sale, Order]
      can :read, [Product, Worker, Sale], office_id: worker.office.id
      can :manage, [Sale], worker_id: worker.id
      can :edit, [Sale], office_id: worker.office.sales.ids
      can :manage, [Order], sale_id: worker.sales.ids
    end
  end
end

app/models/admin_ability.rb
# frozen_string_literal: true

class AdminAbility
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/commerce.rb
class Commerce < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offices, dependent: :destroy
  has_many :workers, dependent: :destroy
  has_many :sales, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :rol, presence: true, uniqueness: true
  validates :name, presence: true

  def self.find_orders_ids(commerce)
    orders = []
    commerce.offices.each do |office|
      office.sales.each do |sale |
        sale.orders.each do |order|
          orders << order.id
        end
      end
    end
    orders
  end
end

app/models/commerce_ability.rb
# frozen_string_literal: true

class CommerceAbility
  include CanCan::Ability

  def initialize(commerce)
      can :create, [Worker, Office, Sale, Order, Table, Product]
      can [:manage], [Worker, Office], commerce_id: commerce.id
      can [:manage], [Sale, Product, Table], office_id: commerce.offices.ids
      can [:manage], [Order], sale_id: Commerce.find_orders_ids(commerce)
  end
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :commerce
  has_many :workers, dependent: :nullify
  has_many :sales, dependent: :nullify
  has_many :products, dependent: :destroy
  has_many :tables, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :name, presence: true

  def self.find_month_sales(office)
    date = Date.today
    office.sales.where(:created_at => date.at_beginning_of_month..date.at_end_of_month)
  end

  def self.find_year_sales(office)
    date = Date.today
    office.sales.where(:created_at => date.at_beginning_of_year..date.at_end_of_year)
  end

  def self.find_today_sales(office)
    date = Date.today
    office.sales.where(:created_at => date.at_beginning_of_day..date.at_end_of_day)
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :sale

  validates :quantity, presence: true
  validates :amount, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :office
  has_many :orders, dependent: :destroy
  has_many :sales, through: :orders
  has_one_attached :image, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :worker, optional: true
  belongs_to :table, optional: true
  belongs_to :office, optional: true
  belongs_to :commerce
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  validates :total, presence: true
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :sales, dependent: :nullify
  belongs_to :office

  validates :description, presence: true
end

app/models/worker.rb
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :office, optional: true
  belongs_to :commerce
  has_many :sales, dependent: :nullify
  has_one_attached :image, dependent: :destroy

  validates :rol, uniqueness: true, presence: true
  validates :name, presence: true
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def resource_name
    :worker
  end

  def resource
    @resource ||= Worker.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:worker]
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/shared/_alerts.html.erb
<% if alert || notice %>
  <script type="application/javascript">
    $(document).ready( function () {
        $('.modal-title').html('');
        $('.modal-body').html("<div class=\"alert alert-<%= if alert then 'warning' else 'success' end %> fade show text-center\" role=\"alert\">\n" +
            "  <strong><%= alert %><%= notice %></strong>\n" +
            "</div>");
        $('#Modal').modal('show')
    });
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="kilimanjaro_area text-center">
  <!-- Top Footer Area Start -->
  <div class="foo_top_header_one section_padding_100_70">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
          <div class="kilimanjaro_part">
            <h5>Nosotros</h5>
            <p>Somos un equipo joven y apasionado por la informática</p>
            <p>Kitchain es nuestra primera creación</p>
          </div>
          <div class="kilimanjaro_part m-top-15">
            <h5>Social Links</h5>
            <ul class="kilimanjaro_social_links">
              <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
              <li><a href="#"><i class="fab fa-twitter-square"></i> Twitter</a></li>
              <li><a href="#"><i class="fab fa-pinterest-square"></i> Pinterest</a></li>
              <li><a href="#"><i class="fab fa-youtube"></i> YouTube</a></li>
              <li><a href="#"><i class="fab fa-linkedin"></i> Linkedin</a></li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <div class="kilimanjaro_part">
            <h5>Links</h5>
            <ul class="kilimanjaro_links">
              <li><a href="<%= root_url %>"><i class="fa fa-angle-right" aria-hidden="true"></i>Home</a></li>
              <li><a href="<%= features_url %>"><i class="fa fa-angle-right" aria-hidden="true"></i>Características</a></li>
              <li><a href="<%= pricing_url %>"><i class="fa fa-angle-right" aria-hidden="true"></i>Precios</a></li>
              <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Cuenta Empresa</a></li>
              <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Cuenta Trabajador</a></li>
              <li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Foro y Comunidad</a></li>
              <li><%= link_to 'Active Admin', new_admin_user_session_path, class:'btn btn-dark text-black' %></li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <div class="kilimanjaro_part">
            <h5>Contacto</h5>
            <div class="kilimanjaro_single_contact_info">
              <h5>Teléfono:</h5>
              <p>+255 789 54 50 40 <br> +2255 766 90 94 00</p>
            </div>
            <div class="kilimanjaro_single_contact_info">
              <h5>Email:</h5>
              <p>support@kitchain.com <br> business@kitchain.com</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer Bottom Area Start -->
  <div class=" kilimanjaro_bottom_header_one section_padding_50 text-center">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <p>© All Rights Reserved by <a href="#">SC Informatics<i class="fa fa-love"></i></a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_modal.html.erb
<div class="modal fade bd-example-modal-lg" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header bg-info text-white">
        <h5 class="modal-title" id="ModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
 <%= link_to 'Kitchain', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(features_path) %>">
        <%= link_to 'Características', features_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(pricing_path) %>">
        <%= link_to 'Precios', pricing_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle"></i> Cuenta
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if commerce_signed_in? %>
             <%= link_to "Perfil", edit_commerce_registration_path, class:'dropdown-item' %>
             <%= link_to 'Dashboards', dashboards_commerce_path, class:'dropdown-item'%>
             <%= link_to 'Salir', destroy_commerce_session_path, class:'dropdown-item', method: :delete %>
          <% elsif worker_signed_in? %>
             <%= link_to "Perfil", edit_worker_registration_path, class:'dropdown-item' %>
             <%= link_to 'Dashboards', dashboards_workers_path, class:'dropdown-item'%>
             <%= link_to 'Salir', destroy_worker_session_path, class:'dropdown-item', method: :delete %>
          <% else %>
             <%= link_to 'Registro Empresa', new_commerce_registration_path, data:{remote: true}, class:'dropdown-item' %>
             <%= link_to 'Acceso Empresa', new_commerce_session_path, data: {remote: true}, class:'dropdown-item' %>
             <%= link_to 'Acceso Trabajador', new_worker_session_path, data: {remote: true}, class:'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>
<br><br>