config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables, only: [:create, :edit, :destroy]
  patch 'payed/:id', to: 'sale_updates#payed', as: 'payed'
  patch 'given/:id', to: 'sale_updates#given', as: 'given'
  patch 'ready/:id', to: 'sale_updates#ready', as: 'ready'
  patch 'done/:id', to: 'sale_updates#done', as: 'done'
  resources :orders, only: [:create]
  resources :tables, only: [:new, :create, :destroy, :edit, :update]
  delete 'orders/:id', to: 'orders#delete', as: 'delete_order'
  get 'dashboards/commerce', to: 'dashboards#commerce_index'
  get 'dashboards/commerce_sales'
  get 'dashboards/commerce_kitchen'
  get 'dashboards/commerce_generals'
  get 'dashboards/workers', to: 'dashboards#workers_index'
  get 'dashboards/workers_kitchen'
  get 'dashboards/workers_products'
  get 'dashboards/workers_sales'
  resources :orders, only: [:create, :delete]
  resources :sales
  resources :orders, only: [:update, :delete]
  resources :products
  devise_for :workers, controllers:
      {registrations: 'workers/registrations',
      sessions: 'workers/sessions',
      passwords: 'workers/passwords'}
  resources :workers
  resources :offices
  devise_for :commerces, controllers:{
      registrations: 'commerces/registrations',
      sessions: 'commerces/sessions',
  passwords: 'commerces/passwords'}
  resources :commerces
  get 'landing', to: 'landing#index'
  get 'landing/features', to: 'landing#features', as: 'features'
  get 'landing/pricing', to: 'landing#pricing', as: 'pricing'
  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_authorization_check
  before_action :authenticate_commerce!, only: [:commerce_index, :commerce_sales, :commerce_kitchen, :commerce_generals]
  before_action :authenticate_worker!, only: [:workers_index, :workers_kitchen, :workers_sales, :workers_products, :workers_tables]
  before_action :find_commerce_params, only: [:commerce_index, :commerce_sales, :commerce_kitchen, :commerce_generals]
  before_action :find_worker_params, only: [:workers_index, :workers_products, :workers_sales, :workers_tables]
  def commerce_index
  end

  def commerce_sales
    date = Date.today
    start_date = date.at_beginning_of_month
    end_date = date.at_end_of_month
    @commerce_month_sales = @sales.where(:created_at => start_date..end_date)
    @commerce_year_sales = @sales.where(:created_at => date.at_beginning_of_year..date.at_end_of_year)
    @commerce_today_sales = @commerce_month_sales.where(created_at: date.at_beginning_of_day..date.at_end_of_day)
    @commerce_sale_chart = {general: @sales.sum {|sale| sale.total}, año: @commerce_year_sales.sum {|sale| sale.total}, mes: @commerce_month_sales.sum{|sale| sale.total}, hoy: @commerce_today_sales.sum{|sale| sale.total}}
    @commerce_office_sales = {}
    @offices.each {|office| @commerce_office_sales[office.name] = office.sales.sum {|sale| sale.total}}
  end

  def commerce_kitchen
    @best_sale = @orders.group(:product_id).sum(:quantity)
    @best_sale_products = {}
    @best_sale.each do |k,v|
      @best_sale_products[@products.find(k)] = v
    end
    @best_sale_products = @best_sale_products.sort_by{|k, v| v}
    @best_sale_chart = @best_sale_products.map{|product, value| [product.name, value]}
    @best_offices_orders = {}
    @offices.each do |office|
      @best_offices_orders[office.name] = office.sales.sum {|sale| sale.orders.count}
    end
  end

  def commerce_generals
  end

  def workers_index
    @worker_month_sales = @worker.sales.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month)
  end

  def workers_kitchen
    @sales = current_worker.office.sales
  end

  def workers_products
  end

  def workers_sales
    @sale = Sale.new
  end

  private

  def find_commerce_params
    @commerce = current_commerce
    @offices = @commerce.offices
    @products = Product.where(office_id: @offices.ids)
    @workers = @commerce.workers
    @sales = @commerce.sales
    @orders = Order.where(sale_id: @sales.ids, product_id: @products.ids)
  end

  def find_worker_params
    @worker = current_worker
    @commerce = current_worker.commerce
    @office = current_worker.office
    @products = @office.products
    @sales = @worker.sales
    @orders = @sales.orders
    @tables = @office.tables
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def resource_name
    :worker
  end

  def resource
    @resource ||= Worker.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:worker]
  end
end

app/views/dashboards/commerce_generals.html.erb
<%= render 'commerces/shared/navbarcommerce' %>
<br><br>
<div class="container card bg-info text-center">
  <br>
  <h1 class="text-white"> Tiempo Real</h1>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <br>
        <h2> Ventas </h2>
        <hr>
        <div id="realsales">
          <%= render @sales.max(6) %>
        </div>
        <br>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <br>
        <h2> Ordenes</h2>
        <hr>
        <div id="realorders">
          <%= render @orders.order(created_at: :desc).max(15) %>
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>
  <div class="">
    <div class="card">
      <br>
      <h2> Ventas por Sucursal</h2>
      <hr>
      <div id="realoffices">
        <%= render @offices %>
      </div>
      <br>
    </div>
  </div>
</div>

<script type="application/javascript">
    $(document).on('ready turbolinks:load', function () {
        realtime = setInterval(function () {
            if (window.location.pathname == '/dashboards/commerce_generals'){
                $.ajax({
                    url: '/dashboards/commerce_generals',
                    type: 'GET',
                    dataType: 'script'
                });
            } else {
                clearInterval(realtime)
            }

        }, 5000)
    });
</script>

app/views/dashboards/commerce_generals.js.erb
$('#realsales').html('<%= j render @sales.order(created_at: :desc).max(6) %>')
$('#realorders').html('<%= j render @orders.order(created_at: :desc).max(15) %>')
$('#realoffices').html('<%= j render @offices %>')

app/views/dashboards/commerce_index.html.erb
<%= render 'commerces/shared/navbarcommerce' %>
<br><br>

  <div class="container text-center card bg-info">
    <br>
    <h1 class="text-center text-white"> Bienvenido <%= current_commerce.name %></h1>
    <br>
    <hr>

    <div class="card p-1">
      <br>
      <h1 class="text-center">Tus sucursales </h1>
      <hr>
      <h3 class="m-0 p-0"> <%= link_to 'Nueva Sucursal', new_office_path, data:{remote:true}, class:'btn btn-primary col-sm-12', style:'position: unset' %></h3>
      <br>
      <div style="overflow-x:auto" class="p-3">
        <table class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
          <thead>
          <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Número</th>
            <th>Trabajadores</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
            <%= render @offices %>
          </tbody>
        </table>
      </div>
      <br>
    </div>
    <br>


    <div class="card">
      <br>
      <h1 class="text-center">Tus trabajadores </h1>
      <hr>
      <h3 class="m-0 p-0"> <%= link_to 'Nuevo trabajador', new_worker_path ,data: {remote:true}, class:'btn btn-primary col-sm-12', style:'position: unset' %></h3>
      <br>
      <div style="overflow-x:auto " class="p-3">
        <table class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
          <thead >
          <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Sucursal</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%= render @workers %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/dashboards/commerce_kitchen.html.erb
<%= render 'commerces/shared/navbarcommerce' %>
<br><br>
<div class="container bg-info text-center">
  <br>
  <h1 class="text-white"> Cocina y productos </h1>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="card p-3" style="overflow-x:auto">
        <br>
        <h2> Tus Productos</h2>
        <br>
        <table class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
          <thead>
          <tr>
            <th scope="col">Producto</th>
            <th scope="col">Precio</th>
            <th scope="col">Stock</th>
            <th scope="col">Sucursal</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%= render @products %>
          </tbody>
        </table>
      </div>

      <br>

      <div class="card p-3" style="overflow-x:auto">
        <br>
        <h2>Ventas por productos</h2>
        <hr>
        <table  class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
          <thead>
          <tr>
            <th scope="col">Producto</th>
            <th scope="col">Precio</th>
            <th scope="col">Cantidad vendida</th>
          </tr>
          </thead>
          <tbody>
          <% @best_sale_products.reverse_each do |product, value| %>
            <tr>
              <td><%= product.name %></td>
              <td>$<%= product.price %></td>
              <td><%= value %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <br>
    </div>

    <div class="col-sm-6">
      <div class="card p-3" style="overflow-x:auto">
        <br>
        <h2> Últimas órdenes</h2>
        <br>
        <table  class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
          <thead>
          <tr>
            <th scope="col">Trabajador</th>
            <th scope="col">Monto</th>
            <th scope="col">Producto</th>
            <th scope="col">Cantidad</th>
          </tr>
          </thead>
          <tbody>
        <% @orders.each do |order| %>
            <tr>
              <td><%= order.sale.worker.name %></td>
              <td>$<%= order.amount %></td>
              <td><%= order.product.name if order.product %></td>
              <th><%= order.quantity %></th>
            </tr>
        <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <div class="card">
        <br>
        <h2> Oficinas/Órdenes </h2>
        <div class="p-4"><%= bar_chart @best_offices_orders, messages: {empty: "No hay datos"} %></div>
      </div>
      <br>
      <div class="card">
        <br>
        <h2> Productos/Ventas </h2>
        <div class="p-4"><%= bar_chart @best_sale_chart, messages: {empty: "No hay datos"} %></div>
      </div>
    </div>

  </div>
</div>

app/views/dashboards/commerce_sales.html.erb
<%= render 'commerces/shared/navbarcommerce' %>
<br><br>
<div class="container bg-info togglex">
  <br>
  <h1 class="text-white text-center"> Tu dashboard de ventas</h1>
  <br>
  <div class="card p-3 text-center" style="overflow-x:auto">
    <br>
    <h2> Rendimiento de tus sucursales </h2>
    <hr>
    <table class="table table-striped table-bordered table-sm dtBasicExample" cellspacing="0">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Sucursal</th>
        <th scope="col">Trabajadores</th>
        <th scope="col">Ventas</th>
        <th scope="col">% Ventas Totales</th>
      </tr>
      </thead>
      <tbody>
      <% @offices.each do |office| %>
        <tr>
          <th scope="row"><%= office.id %></th>
          <td><%= office.name %></td>
          <td><%= office.workers.count %></td>
          <td><%= number_to_currency( office.workers.sum {|worker| worker.sales.sum {|sale| sale.total} }, precision: 0) %></td>
          <td><%= number_to_percentage((((office.sales.sum {|sale| sale.total}).to_f / @sales.sum {|sale| sale.total})*100), precision: 2)  %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <div class="card p-3">
    <br>
    <h2> Ventas por oficina (Total) </h2>
    <hr>
    <div class="p-4"><%= bar_chart @commerce_office_sales, prefix: "$", messages: {empty: "No hay datos"}  %></div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6 text-center">
      <div class="card">
      <br>
      <h2> Ventas totales </h2>
      <hr>
      <table class="table table-striped" cellspacing="0">
        <thead>
        <tr>
          <th scope="col">Ventas</th>
          <th scope="col">Total</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th>General:</th>
          <th><%=number_to_currency(@sales.sum {|sale| sale.total}, precision: 0) %></th>
        </tr>
        <tr>
          <th>Este Año:</th>
          <th><%=number_to_currency(@commerce_year_sales.sum {|sale| sale.total}, precision: 0) %></th>
        </tr>
        <tr>
          <th>Este Mes:</th>
          <th><%=number_to_currency(@commerce_month_sales.sum {|sale| sale.total}, precision: 0) %></th>
        </tr>
        <tr>
          <th>Hoy:</th>
          <th><%=number_to_currency(@commerce_today_sales.sum {|sale| sale.total}, precision: 0) %></th>
        </tr>
        </tbody>
      </table>
    </div>
    </div>
    <br>
    <div class="col-sm-6 text-center">
      <div class="card">
        <br>
        <h2> Gráfico de ventas </h2>
        <hr>
        <div class="p-4"><%= bar_chart @commerce_sale_chart, prefix: "$", messages: {empty: "No hay datos"}  %></div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/workers_index.html.erb
<%= render 'workers/shared/navbarworker' %>
<br><br>
<div class="container">
  <div class="card">
    <br>
    <h1 class="text-center"> Bienvenid@ <%= @worker.name %> </h1>
    <hr>
    <div class="row text-center">
      <div class="col-sm-6">
        <h4>Mis datos</h4>
        <% if current_worker.image.attached? %>
          <%= image_tag(current_worker.image, class:"img-thumbnail") %>
        <% else %>
          <%= image_tag('https://definicionde.es/wp-content/uploads/2019/04/definicion-de-persona-min.jpg', class:'img-thumbnail') %>
        <% end %>
        <div class="row">
          <div class="col-sm-6 text-center pl-4">
            Nombre: <%= @worker.name %> <br>
            Email: <%= @worker.email %> <br>
            Ventas este mes: <%= @worker_month_sales.count %> | $<%= @worker_month_sales.sum {|sale| if sale.total then  sale.total else 0 end} %>
          </div>
          <div class="col-sm-6">
            <%= link_to 'Editar perfil', edit_worker_registration_path, data: {remote: true} %><br>
            <%= link_to 'Ventas', dashboards_workers_sales_path %> <br>
            <%= link_to 'Cocina', dashboards_workers_kitchen_path %>
          </div>
        </div>

      </div>
      <div class="col-sm-6">
        <h4> Últimas Ventas </h4>
        <% @worker.sales.order(created_at: :desc).max(5).each do |sale| %>
          <div class="card">
            Total: <%= number_to_currency(sale.total, precision: 0)  %> |
            Productos: <% sale.products.each do |product| %>
              <%= product.name %> -
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="row p-3">
      <div class="col-sm-4 text-center">
        <h3 class="text-center">Empresa: <%= @commerce.name %></h3>
        <% if @commerce.image.attached? %>
          <%= image_tag(@commerce.image) %>
        <% else %>
          <%= image_tag('http://comunidad.iebschool.com/iebs/files/2015/04/employer-branding.png') %>
        <% end %>
        Dirección: <%= @commerce.adress %> <br>
        Trabajadores: <%= @commerce.workers.count %> <br>
        Sucursales: <%= @commerce.offices.count %>
      </div>

      <div class="col-sm-4 text-center">
        <h3 class="text-center"><%= @office.name %></h3>
        <% if @office.image.attached? %>
          <%= image_tag(@office.image) %>
        <% else %>
          <%= image_tag('https://cdn.shopify.com/s/files/1/0360/9813/files/Untitled-1-08_c5cd3da8-efef-4641-9a62-183077766342.jpg?v=1494396790') %>
        <% end %>
        Dirección: <%= @office.adress %> <br>
        Trabajadores: <%= @office.workers.count %> <br>
        Ventas: <%= @office.sales.count %>
      </div>

      <div class="col-sm-4 text-center">
        <h3 class="text-center">Productos: <%= @products.count %></h3>
        <%= image_tag('https://images.clarin.com/2018/11/19/IOjeiwK-3_1256x620__1.jpg') %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/dashboards/workers_kitchen.html.erb
<%= render 'workers/shared/navbarworker' %>
<br><br>
<div class="container">
  <div class="card bg-gray">
    <br>
    <h1 class="text-center"> Cocina </h1>
    <hr>
    <div class="text-center">
      <div class="" id="kitchen_sales">
        <% @sales.where(state: [1,2,3]).order(:created_at).each do |sale| %>
          <div class="container" id="sale_<%= sale.id %>_container">
            <div class="card" style="min-height: 5vh">
              <small>
                <b>Total: </b><%= number_to_currency(sale.total, precision: 0)  %>
                <b id="payed_<%= sale.id %>">Pagado: <%= if sale.payed? then 'Si' else 'No' end %></b>
                <b>Productos: </b>
                <% sale.orders.each do |order| %>
                  <%= order.quantity %> <%= order.product.name %> |
                <% end %>
                <div class="card d-inline">
                  <b>Comentario: </b><%= sale.comment %>
                </div>
                <div id="state_<%= sale.id %>">
                  <% case sale.state %>
                  <% when 1 %>
                    <div class="alert alert-primary p-0 w-25 d-inline">
                      Pedido Solicitado
                    </div>
                  <% when 2 %>
                    <div class="alert alert-success p-0 w-25 d-inline">
                      Pedido Preparado
                    </div>
                  <% when 3 %>
                    <div class="alert alert-warning p-0 w-25 d-inline">
                      Pedido Entregado
                    </div>
                  <% end %>
                </div>
                <%= link_to '¿Pedido listo?', ready_path(sale.id), method: :patch ,data: {remote: true}, class:'alert alert-info w-25 p-0 d-inline' %>
              </small>
            </div>
          </div>
          <div class="p-1"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript">
    $(document).on('ready turbolinks:load', function () {
        workerkitchen = setInterval(function () {
            if(window.location.pathname == '/dashboards/workers_kitchen'){
                $.ajax({
                    url: '/dashboards/workers_kitchen',
                    type: 'GET',
                    dataType: 'script'
                });
            } else {
                clearInterval(workerkitchen)
            }
        }, 5000)
    });
</script>

app/views/dashboards/workers_kitchen.js.erb
$('#kitchen_sales').html('<% @sales.where(state: [1,2,3]).order(:created_at).each do |sale| %>\n' +
    '          <div class="container" id="sale_<%= sale.id %>_container">\n' +
    '            <div class="card" style="min-height: 5vh">\n' +
    '              <small>\n' +
    '                <b>Total: </b><%= number_to_currency(sale.total, precision: 0)  %>\n' +
    '                <b id="payed_<%= sale.id %>">Pagado: <%= if sale.payed? then "Si" else "No" end %></b>\n' +
    '                <b>Productos: </b>\n' +
    '                <% sale.orders.each do |order| %>\n' +
    '                  <%= order.quantity %> <%= order.product.name %> |\n' +
    '                <% end %>\n' +
    '                <div class="card d-inline">\n' +
    '                  <b>Comentario: </b><%= sale.comment %>\n' +
    '                </div>\n' +
    '                <div id="state_<%= sale.id %>">\n' +
    '                  <% case sale.state;  when 1%>\n' +
    '                    <div class="alert alert-primary p-0 w-25 d-inline">\n' +
    '                      Pedido solicitado\n' +
    '                    </div>\n' +
    '                  <% when 2 %>\n' +
    '                    <div class="alert alert-success p-0 w-25 d-inline">\n' +
    '                      Pedido Preparado\n' +
    '                    </div>\n' +
    '                  <% when 3 %>\n' +
    '                    <div class="alert alert-warning p-0 w-25 d-inline">\n' +
    '                      Pedido Entregado\n' +
    '                    </div>\n' +
    '                  <% end %>\n' +
    '                </div>\n' +
    '                <%= link_to '¿Pedido listo?', ready_path(sale.id), method: :patch ,data: {remote: true}, class:'alert alert-info w-25 p-0 d-inline' %>\n' +
    '              </small>\n' +
    '            </div>\n' +
    '          </div>\n' +
    '          <div class="p-1"></div>\n' +
    '        <% end %>')

app/views/dashboards/workers_products.html.erb
<%= render 'workers/shared/navbarworker' %>
<div class="container">
  <div class="card text-center">
    <br>
    <h1>Productos</h1>
    <br>
    <%= link_to 'Crear producto', new_product_path ,data: {remote: true}, class:'btn btn-primary col-sm-10 mx-auto p-2', style: 'position: unset' if @worker.admin %>
    <div id="kitchenproducts">
      <% current_worker.office.products.each_slice(3) do |products| %>
        <div class="card-deck p-3">
          <% products.each do |product| %>
            <div class="card" id="product_<%= product.id %>">
              <% if product.image.attached? %>
                <%= image_tag(product.image, class:"card-img img-thumbnail") %>
              <% else %>
                <img src="https://concepto.de/wp-content/uploads/2015/03/alimentos-e1549655531380.jpg" class="card-img-top" alt="...">
              <% end %>
              <div class="card-body">
                <h5 class="card-title"> <%= product.name %></h5>
                <p class="card-text" id="product_<%= product.id %>_quantity">
                  $<%= product.price %> | Cantidad: <%= if product.quantity.to_i > 0 then product.quantity else 'Sin stock' end %>
                  <% if current_worker.admin %>
                    <%= link_to 'Editar', edit_product_path(product.id), data: {remote: true}, class:'btn btn-warning p-2', style: 'position: unset' %>
                    <%= link_to 'Eliminar', product, method: :delete, data: {confirm: 'Se eliminarán todos los datos de este product', remote: true}, class:'btn btn-danger p-2', style: 'position: unset' %>
                  <% end %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
      </div>
      <div class="card">
        <br>
        <h1 class="text-center"> Mesas </h1>
        <br>
        <%= link_to 'Crear Mesa', new_table_path, data: {remote: true}, class:'btn btn-primary col-sm-10 mx-auto p-2', style: 'position: unset' if @worker.admin %>
        <div id="tables">
          <%current_worker.office.tables.order(:created_at).each_slice(3) do |tables|%>
            <div class="card-deck p-3">
              <% tables.each do |table| %>
                <%= render table%>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      </div>
<br><br>

app/views/dashboards/workers_sales.html.erb
<%= render 'workers/shared/navbarworker' %>
<br><br>
<div class="container">
  <div class="card bg-gray">
    <br>
    <h1 class="text-center"> Tu Dashboard </h1>
    <hr>
      <div class="text-center">
        <h2> Crear nueva venta</h2>
        <%= render 'sales/new' %>
      </div>

      <div class="text-center">
        <h2> Ventas Activas </h2>
        <div id="sales">
          <%= render @sales.where(state: [1,2,3]).order(:created_at) %>
        </div>
      </div>
    </div>
  </div>
<script type="application/javascript">
    $(document).on('ready turbolinks:load', function () {
        workersale = setInterval(function () {
            if(window.location.pathname == "/dashboards/workers_sales"){
                $.ajax({
                    url: '/dashboards/workers_sales',
                    type: 'GET',
                    dataType: 'script'
                });
            } else {
                clearInterval(workersale)
            }
            }, 1000)
    });
</script>

app/views/dashboards/workers_sales.js.erb
$('#sales').html('<%= j render current_worker.sales.where(state: [1,2,3]).order(:created_at) %>')