config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tables, only: [:create, :edit, :destroy]
  patch 'payed/:id', to: 'sale_updates#payed', as: 'payed'
  patch 'given/:id', to: 'sale_updates#given', as: 'given'
  patch 'ready/:id', to: 'sale_updates#ready', as: 'ready'
  patch 'done/:id', to: 'sale_updates#done', as: 'done'
  resources :orders, only: [:create]
  resources :tables, only: [:new, :create, :destroy, :edit, :update]
  delete 'orders/:id', to: 'orders#delete', as: 'delete_order'
  get 'dashboards/commerce', to: 'dashboards#commerce_index'
  get 'dashboards/commerce_sales'
  get 'dashboards/commerce_kitchen'
  get 'dashboards/commerce_generals'
  get 'dashboards/workers', to: 'dashboards#workers_index'
  get 'dashboards/workers_kitchen'
  get 'dashboards/workers_products'
  get 'dashboards/workers_sales'
  resources :orders, only: [:create, :delete]
  resources :sales
  resources :orders, only: [:update, :delete]
  resources :products
  devise_for :workers, controllers:
      {registrations: 'workers/registrations',
      sessions: 'workers/sessions',
      passwords: 'workers/passwords'}
  resources :workers
  resources :offices
  devise_for :commerces, controllers:{
      registrations: 'commerces/registrations',
      sessions: 'commerces/sessions',
  passwords: 'commerces/passwords'}
  resources :commerces
  get 'landing', to: 'landing#index'
  get 'landing/features', to: 'landing#features', as: 'features'
  get 'landing/pricing', to: 'landing#pricing', as: 'pricing'
  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :worker, optional: true
  belongs_to :table, optional: true
  belongs_to :office, optional: true
  belongs_to :commerce
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  validates :total, presence: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  load_and_authorize_resource
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.worker = current_worker
    @sale.office = current_worker.office
    @sale.total = 0
    @sale.state = 1
    if worker_signed_in?
      @sale.commerce = current_worker.commerce
    else
      @sale.commerce = current_commerce.id
    end
    respond_to do |format|
      if @sale.save
        format.js
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:worker_id, :total, :payed, :comment, :table_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Mesa*' %>
    <%= form.select :table_id, @tables.pluck(:description, :id), sales_table_id: :id %>
  </div>
<hr>
  <div class="actions">
    <%= form.submit 'Enviar', class:'btn btn-primary col-sm-10 mx-auto' %>
  </div>
<% end %>
<br>

app/views/sales/_new.html.erb
<%= render 'sales/form', sale: @sale %>

app/views/sales/_sale.html.erb
<% if current_worker %>
  <div class="container" id="sale_<%= sale.id %>_container">
    <div class="card" style="min-height: 5vh">
      <small>
        <b>Total: </b><%= number_to_currency(sale.total, precision: 0)  %>
        <b id="payed_<%= sale.id %>">Pagado: <%= if sale.payed? then 'Si' else 'No' end %></b>
        <b>Productos: </b>
        <% sale.orders.each do |order| %>
          <%= order.quantity %> <%= order.product.name %> <%= link_to 'x', delete_order_path(order.id), method: :delete, data: {remote: true}, style:'color: red'  %>  |
        <% end %>
        <div class="card d-inline">
          <b>Comentario: </b><%= sale.comment %>
        </div>
        <div id="state_<%= sale.id %>">
          <% case sale.state %>
          <% when 1 %>
            <div class="alert alert-primary p-0 w-25 d-inline">
              Pedido solicitado
            </div>
          <% when 2 %>
            <div class="alert alert-success p-0 w-25 d-inline">
              Pedido listo
            </div>
          <% when 3 %>
            <div class="alert alert-warning p-0 w-25 d-inline">
              Pedido Entregado
            </div>
          <% end %>
        </div>
        <%= link_to 'Ver venta', sale,data: {remote: true}, class:'alert alert-success w-25 p-0 d-inline'  %>
        <%= link_to 'Eliminar Venta', sale, method: :delete, data: {confirm: 'Se eliminará esta venta', remote: true}, class:'alert alert-danger w-25 p-0 d-inline' %>
        <%= link_to '¿Pagado?', payed_path(sale.id),method: :patch ,data: {remote: true}, class:'alert alert-info w-25 p-0 d-inline', id:'payed' %>
        <% if sale.state == 2 %>
          <%= link_to '¿Entregado?', given_path(sale.id),method: :patch,data: {remote: true}, class:'alert alert-info w-25 p-0 d-inline', id:'given' %>
        <% elsif sale.state == 3 %>
          <%= link_to 'Finalizar', done_path(sale.id),method: :patch ,data: {confirm: 'La venta desaparecerá después de esta acción',remote: true}, class:'alert alert-info w-25 p-0 d-inline', id:'payed' %>
        <% end %>
      </small>
    </div>
  </div>
  <div class="p-1"></div>
<% else %>
  <div class="container" style="min-width: 107px">
    <div class="card">
      <b>Sucursal: <%= sale.office.name if sale.office %></b>
      <small>
        <b>Trabajador: </b><%= sale.worker.name %>
        <b>Total: </b><%= number_to_currency(sale.total, precision: 0)  %>
        <b>Productos: </b>
        <% sale.orders.each do |order| %>
          <%= order.quantity %> <%= order.product.name %>  |
        <% end %>
      </small>
    </div>
  </div>
<% end %>

app/views/sales/_show.html.erb
<p id="notice"><%= notice %></p>

<p class="form-group">
  <strong>Total:</strong>
  <div id="sale_<%=@sale.id%>_total" class="form-control">$<%= @sale.total %></div>
</p>

<%= form_with(model: @sale) do |f| %>
<p class="form-group">
  <%= f.label 'Comentario' %>
  <%= f.text_field :comment, class:'form-control' %>
</p>
  <%= f.submit 'Guardar comentario' %>
<% end %>
<div id="alerts"></div>

<p class="form-group">
  <strong>Mesa:</strong>
<div class="form-control"><%= @sale.table.description %></div>
</p>

<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Productos</h1>
  <% current_worker.office.products.each_slice(3) do |products| %>
    <div class="card-deck">
      <% products.each do |product| %>
        <div class="card">
          <% if product.image.attached? %>
            <%= image_tag(product.image, class:"card-img img-thumbnail") %>
          <% else %>
            <img src="https://concepto.de/wp-content/uploads/2015/03/alimentos-e1549655531380.jpg" class="card-img-top" alt="...">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"> <%= product.name %></h5>
            <p class="card-text" id="product_<%= product.id %>_quantity">$<%= product.price %> | Cantidad: <%= if product.quantity.to_i > 0 then product.quantity else 'Sin stock' end %></p>
            <% if product.quantity.to_i > 0 %>
              <div id="product_<%= product.id %>">
                <%= form_with model: Order.new do |f| %>
                  <%= f.label 'Cantidad' %>
                  <%= f.select :quantity, (1..20).map {|i| [i,i]} %>
                  <%= f.hidden_field :sale_id, value: @sale.id %>
                  <%= f.hidden_field :product_id, value: product.id %>
                  <%= f.submit 'Agregar', class:'btn btn-success' %>
                <%end%>
              <% else %>
              <div class="alert alert-danger" role="alert">
                Producto sin stock
              </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/sales/create.js.erb
$('#sales').append('<%= j render @sale %>');
$('#ModalLabel').html("Agregar productos a venta")
$('.modal-body').html("<%= j render 'sales/show' %>");
$('#Modal').modal('show');

app/views/sales/destroy.js.erb
$("#sale_<%= @sale.id %>_container").toggle

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Worker</th>
      <th>Total</th>
      <th>Payed</th>
      <th>Comment</th>
      <th>Table</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.worker %></td>
        <td><%= sale.total %></td>
        <td><%= sale.payed %></td>
        <td><%= sale.comment %></td>
        <td><%= sale.table %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.js.erb
$('#sales').append('<%= j render @sale %>')

app/views/sales/show.js.erb
$('#ModalLabel').html("Agregar productos a venta")
$('.modal-body').html("<%= j render 'sales/show' %>");
$('#Modal').modal('show');

app/views/sales/update.js.erb
$('#alerts').html('<div class="alert alert-info">\n' +
    '  Comentario actualizado\n' +
    '</div>')
$('#sale_comment').val('<%= @sale.comment %>')